---
namespace: mrlesmithjr
name: netbox
version: 1.0.1
# build_ignore:
#   - venv/
#   - group_vars/
#   - "*.tar.gz"
readme: README.md
authors:
  - Larry Smith Jr. <mrlesmithjr@gmail.com>
description: Ansible collection for installing/configuring/managing NetBox
license_file: "LICENSE.md"
tags:
  - dcim
  - ipam
  - system
  - networking
dependencies: {}
repository: https://github.com/mrlesmithjr/netbox
documentation: https://github.com/mrlesmithjr/netbox/docs
homepage: https://github.com/mrlesmithjr/netbox
issues: https://github.com/mrlesmithjr/netbox/issues
