- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netbox.netbox
  tasks:
    - name: Manage NetBox IPAM Roles
      netbox_ipam_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_ipam_roles }}"

    - name: Manage NetBox Regions
      netbox_region:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_regions }}"

    - name: Manage NetBox Tenant Groups
      netbox_tenant_group:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_tenant_groups }}"

    - name: Manage NetBox Tenants
      netbox_tenant:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_tenants }}"

    - name: Manage NetBox Sites
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_sites }}"

    - name: Manage NetBox Rack Groups
      netbox_rack_group:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_rack_groups }}"

    - name: Manage NetBox Rack Roles
      netbox_rack_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_rack_roles }}"

    - name: Manage NetBox Racks
      netbox_rack:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_racks }}"

    - name: Manage NetBox Manufacturers
      netbox_manufacturer:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_manufacturers }}"

    - name: Manage NetBox Platforms
      netbox_platform:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_platforms }}"

    - name: Manage NetBox RIRs
      netbox_rir:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_rirs }}"

    - name: Manage NetBox Aggregates
      netbox_aggregate:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_aggregates }}"

    - name: Manage NetBox VRFs
      netbox_vrf:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_vrfs }}"

    - name: Manage NetBox VLAN Groups
      netbox_vlan_group:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_vlan_groups }}"

    - name: Manage NetBox VLANs
      netbox_vlan:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_vlans }}"

    - name: Manage NetBox Prefixes
      netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
        first_available: "{{ item.first_available|default(omit) }}"
      loop: "{{ netbox_prefixes }}"

    - name: Manage NetBox Device Types
      netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_device_types }}"

    - name: Manage NetBox Device Roles
      netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_device_roles }}"

    - name: Manage NetBox Cluster Groups
      netbox_cluster_group:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_cluster_groups }}"

    - name: Manage NetBox Cluster Types
      netbox_cluster_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_cluster_types }}"

    - name: Manage NetBox Clusters
      netbox_cluster:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_clusters }}"

    - name: Manage NetBox Devices
      netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_devices }}"

    - name: Manage NetBox Virtual Machines
      netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_virtual_machines }}"

    - name: Manage NetBox Interfaces
      netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_device_interfaces }}"

    - name: Manage NetBox Virtual Interfaces
      netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_virtual_interfaces }}"

    - name: Manage NetBox IP Addresses
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data: "{{ item.data }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ netbox_ip_addresses }}"
