---
- hosts: all
  tasks:
    - name: Include mrlesmithjr.ansible_bootstrap_python
      include_role:
        name: mrlesmithjr.ansible_bootstrap_python
    - name: Include mrlesmithjr.postgresql
      include_role:
        name: mrlesmithjr.postgresql
    - name: Include mrlesmithjr.redis
      include_role:
        name: mrlesmithjr.redis
    - name: Include mrlesmithjr.ansible_netbox
      include_role:
        name: mrlesmithjr.ansible_netbox

- import_playbook: manage_netbox.yml
