---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: requirements.yml
    roles-path: "${MOLECULE_PROJECT_DIRECTORY}/roles"
    requirements-file: requirements.yml
    collections-path: "${MOLECULE_PROJECT_DIRECTORY}/."
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu1804
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:8080:80/tcp
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  env:
    ANSIBLE_COLLECTIONS_PATHS: "${MOLECULE_PROJECT_DIRECTORY}/."
verifier:
  name: ansible
